### ISSUE TITLE
Kubernetes Incubation Proposal for Kubeclient

### ISSUE THREAD

**Issue by simon3z** [abonas/kubeclient#219]
Reference: https://github.com/kubernetes/community/blob/master/incubator.md

### Problem Statement

Kubernetes is currently missing a Ruby client of reference. Kubeclient is a project started in December 2014 that implements the Kubernetes API for Ruby. Since Q1 2016 with the addition of the api-group support it covers all the discoverable objects and the majority of the verbs of the API.

### Proposed Solution

Kubeclient will continue tracking the evolution of Kubernetes API to enable Ruby applications to interact with Kubernetes.

### Roadmap

- [x] Q1 2015 - Project started
- [x] Q2 2015 - Adopted by ManageIQ as client for Kubernetes
- [x] Q1 2016 - Support for the api-group and OpenShift extensions
- [ ] FUTURE - Continue tracking the evolution of Kubernetes API

## OWNERS
```
assignees:
  - abonas
  - fsimonce
  - mtayer
```

**Comment by smarterclayton** [comment]
Add description of how to converge with client generation, and add points about whether this is inconsistent or not.

Ask the question about how the ruby gems can be built and pushed to the mirrors.  Who does that?

**Comment by simon3z** [comment]
> Add description of how to converge with client generation, and add points about whether this is inconsistent or not.
> 
> Ask the question about how the ruby gems can be built and pushed to the mirrors. Who does that?

@smarterclayton I think these two parts are related. I assume there's a way to auto-generate ruby code from swagger (we'll have to evaluate if that has issues), but even so, is there anyone in Kubernetes already assigned to release Gems? If that's not in place we could converge this client to the auto-generation and provide the Gem generation if that's missing.

**Comment by smarterclayton** [comment]
I don't think you have to *start* with auto gen, just have an answer for how you'd use it / approach it.

Gem generation I don't think is happening, so there may be some concern about approaching it.

**Comment by simon3z** [comment]
@smarterclayton I updated the issue with the info you needed.

**Comment by smarterclayton** [comment]
Looks ok.
